---
galaxy_info:
  author: Migration Tool
  description: Migrated to modern Ansible
  galaxy_tags: []
  license: Apache-2.0
  min_ansible_version: "2.10"
  namespace: x2a
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
        - "10"
  role_name: profile_haproxy
