---
- name: Set environment path for Linux systems
  ansible.builtin.set_fact:
    ansible_env:
      PATH: /usr/bin:/bin:/usr/sbin:/sbin:{{ ansible_env.PATH }}
  when: ansible_facts['kernel'] | lower == 'linux'
- name: Include base profile
  ansible.builtin.include_tasks: base.yml
- name: Include HAProxy profile
  ansible.builtin.include_tasks: haproxy.yml
  when: ansible_facts['kernel'] | lower == 'linux'
