---
controller_credentials:
- name: HAProxy Stats Authentication - profile_haproxy
  description: Credentials for accessing the HAProxy statistics page
  organization: Default
  credential_type: HAProxy Stats Authentication
  update_secrets: true
  inputs:
    stats_user: '{{ stats_user }}'
    stats_password: '{{ vault_stats_password }}'
