---
controller_credential_types:
- name: HAProxy Stats Authentication
  description: Credentials for accessing the HAProxy statistics page
  kind: cloud
  inputs:
    fields:
    - id: stats_user
      type: string
      label: Stats Username
      help_text: Username for accessing the HAProxy statistics page
    - id: stats_password
      type: string
      label: Stats Password
      secret: true
      help_text: Password for accessing the HAProxy statistics page
    required:
    - stats_user
    - stats_password
  injectors:
    extra_vars:
      stats_user: !unsafe '{{ stats_user }}'
      stats_password: !unsafe '{{ stats_password }}'
