---
controller_credential_types:
- name: HAProxy Stats Authentication
  description: Credential type for HAProxy Stats Authentication
  kind: cloud
  inputs:
    fields:
    - id: stats_username
      type: string
      label: Stats Username
      help_text: Username for HAProxy statistics page authentication
    - id: stats_password
      type: string
      label: Stats Password
      secret: true
      help_text: Password for HAProxy statistics page authentication
    required:
    - stats_password
  injectors:
    extra_vars:
      stats_username: !unsafe '{{ stats_username }}'
      stats_password: !unsafe '{{ stats_password }}'
