---
controller_credentials:
- name: HAProxy Stats Authentication - profile
  description: Credential for profile
  organization: Default
  credential_type: HAProxy Stats Authentication
  update_secrets: true
  inputs:
    stats_username: '{{ stats_username }}'
    stats_password: '{{ vault_stats_password }}'
