---
- name: Reload HAProxy
  ansible.builtin.systemd:
    name: "{{ profile_haproxy_service_name }}"
    state: reloaded
- name: Restart HAProxy
  ansible.builtin.systemd:
    name: "{{ profile_haproxy_service_name }}"
    state: restarted
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
